// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmR6B87BMbxEdD0NI86g38mirds20WWa0',
    appId: '1:961059594481:web:bda3c053aff7b2f15c8950',
    messagingSenderId: '961059594481',
    projectId: 'seg-tcc-f84ab',
    authDomain: 'seg-tcc-f84ab.firebaseapp.com',
    storageBucket: 'seg-tcc-f84ab.appspot.com',
    measurementId: 'G-ELPHC950VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzz35W1o3voLEF58Nuui04OhfbqFqJaI',
    appId: '1:961059594481:android:a4858c06fca4fb815c8950',
    messagingSenderId: '961059594481',
    projectId: 'seg-tcc-f84ab',
    storageBucket: 'seg-tcc-f84ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMguu2Zs-w5ZIAihrTMp9g1zdIU48Ke7k',
    appId: '1:961059594481:ios:d24d5cdaa9f318715c8950',
    messagingSenderId: '961059594481',
    projectId: 'seg-tcc-f84ab',
    storageBucket: 'seg-tcc-f84ab.appspot.com',
    iosBundleId: 'com.example.seg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMguu2Zs-w5ZIAihrTMp9g1zdIU48Ke7k',
    appId: '1:961059594481:ios:2599fbeb6449b39e5c8950',
    messagingSenderId: '961059594481',
    projectId: 'seg-tcc-f84ab',
    storageBucket: 'seg-tcc-f84ab.appspot.com',
    iosBundleId: 'com.example.seg.RunnerTests',
  );
}
